# Generated by Django 6.0.2 on 2026-04-22 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('DOB', models.DateField(default=django.utils.timezone.now)),
                ('Subjects', models.CharField(blank=True, choices=[('Mathematical Applications', 'Mathematical Applications'), ('Mathematical Methods', 'Mathematical Methods'), ('Specialist Methods', 'Specialist Methods'), ('Specialist Mathematics', 'Specialist Mathematics')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Area', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Accreditation', models.CharField(max_length=10)),
                ('Unit_Description', models.TextField()),
                ('Unit_Goals', models.TextField()),
                ('Content_Descriptions', models.TextField()),
            ],
        ),
    ]
