# Generated by Django 6.0.2 on 2026-03-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Accreditation', models.CharField(max_length=10)),
                ('UnitDescription', models.CharField(max_length=30)),
                ('UnitGoals', models.CharField(max_length=30)),
                ('Content_Descriptions', models.CharField(max_length=30)),
            ],
        ),
    ]
