# Generated by Django 6.0.2 on 2026-03-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0002_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='UnitDescription',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='UnitGoals',
        ),
        migrations.AddField(
            model_name='unit',
            name='Unit_Description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='Unit_Goals',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='Content_Descriptions',
            field=models.CharField(max_length=300),
        ),
    ]
