# Generated by Django 6.0.2 on 2026-04-22 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0002_remove_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
