# Generated by Django 6.0.2 on 2026-03-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0003_remove_unit_unitdescription_remove_unit_unitgoals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='Content_Descriptions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='unit',
            name='Unit_Description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='unit',
            name='Unit_Goals',
            field=models.CharField(max_length=1000),
        ),
    ]
