# Generated by Django 6.0.2 on 2026-04-22 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0003_remove_student_dob_student_dob2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
