# Generated by Django 6.0.2 on 2026-03-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0004_alter_teacher_email_alter_unit_content_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Subjects', models.CharField(blank=True, choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('IT', 'IT'), ('Chemistry', 'Chemistry')], max_length=30, null=True)),
            ],
        ),
    ]
