# Generated by Django 6.0.2 on 2026-04-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0004_student_dob2'),
    ]

    operations = [
        #migrations.RenameField(model_name='student',old_name='DOB2', new_name='DOB')
    ]
