# Generated by Django 6.0.4 on 2026-05-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0005_migration_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='Subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='Subjects',
            field=models.ManyToManyField(blank=True, to='Page1.subject'),
        ),
    ]
