# Generated by Django 6.0.2 on 2026-03-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Subjects',
            field=models.CharField(blank=True, choices=[('Specialist Mathematics', 'Specialist Mathematics'), ('Specialist Methods', 'Specialist Methods'), ('Mathematical Methods', 'Mathematical Methods'), ('Mathematical Applications', 'Mathematical Applications')], max_length=30, null=True),
        ),
    ]
